name: net-misc/rustdesk-appimage update

permissions:
  contents: write

on:
  schedule:
    - cron: '5 0 * * *'
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/net-misc-rustdesk-appimage-update.yaml'

env:
  ecn: net-misc
  epn: rustdesk-appimage
  repo_owner: rustdesk
  repo_name: rustdesk
  description: "An open-source remote desktop, and alternative to TeamViewer."


jobs:
  check-and-create-ebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget jq coreutils

      - name: Process each release
        id: process_releases
        run: |
          ghrp=${repo_owner}/${repo_name}
          ebuild_dir="./${ecn}/${epn}"
          mkdir -p $ebuild_dir
          releases=$(curl -s https://api.github.com/repos/${repo_owner}/${repo_name}/releases | jq -r '.[].tag_name')
          for release in ${releases}; do
            echo "Processing run number: $run_number"
            version=${release}
            ebuild_file="${ebuild_dir}/${epn}-${version}.ebuild"
            if [ ! -f "$ebuild_file" ]; then
              
              # Create ebuild script
              {
                echo '# rustdesk ebuild file'
                echo 'EAPI=8'
                echo "DESCRIPTION=\"$description\""
                echo "HOMEPAGE=\"https://github.com/${ghrp}\""
                echo 'LICENSE="MIT"'
                echo 'SLOT="0"'
                echo 'KEYWORDS="~amd64 ~arm64"'
                echo 'DEPEND=""'
                echo 'RDEPEND=""'
                echo 'S="${WORKDIR}"'
                echo ''
                echo 'SRC_URI="  '
                echo "  amd64? ( https://github.com/${ghrp}/releases/download/\${release}/rustdesk-\${PV}-x86_64.AppImage -> \$P.amd64 )"
                echo "  arm64? ( https://github.com/${ghrp}/releases/download/\${release}/rustdesk-\${PV}-aarch64.AppImage -> \$P.arm64 )"
                echo '" '
                echo ''
                echo "src_unpack() {"
                echo "  cp \"\${DISTDIR}/\${A}\" \"\${A}\"  || die \"Can't copy archive file\""
                echo "  chmod a+x \"\${A}\"  || die \"Can't chmod archive file\""
                echo "  \"./\${A}\" --appimage-extract rustdesk.desktop || die \"Can't extract .desktop from appimage\""
                echo "  \"./\${A}\" --appimage-extract usr/share/icons || die \"Can't extract icons from app image\""
                echo "}"
                echo ""
                echo "src_prepare() {"
                echo "  sed -i 's:^Exec=.*:Exec=/opt/bin/rustdesk:' squashfs-root/rustdesk.desktop"
                echo "  eapply_user"
                echo "}"
                echo ""
                echo 'src_install() {'
                echo '  mv -v "${DISTDIR}/${A}" rustdesk'
                echo '  exeinto /opt/bin'
                echo '  doexe "rustdesk"'
                echo '  insinto /usr/share/applications'
                echo '  doins "./squashfs-root/rustdesk.desktop"'
                echo '  insinto /usr/share/'
                echo '  doins -r "./squashfs-root/usr/share/icons"'
                echo "}"
                echo ""
                echo "pkg_postinst() {"
                echo "  xdg_desktop_database_update"
                echo "}"
                echo ""
              } > "$ebuild_file"

              # Generate the manifest for the new ebuild
              wget "https://github.com/${ghrp}/releases/download/${release}/rustdesk-${version}-x86_64.AppImage" -O "/tmp/${epn}-${version}.amd64"
              wget "https://github.com/${ghrp}/releases/download/${release}/rustdesk-${version}-aarch64.AppImage" -O "/tmp/${epn}-${version}.arm64"
              
              for e in "${epn}-${version}.amd64" "${epn}-${version}.arm64"; do
                echo "DIST $e $(stat -c %s "/tmp/${e}") BLAKE2B $(b2sum "/tmp/${e}" | cut -d' ' -f1) SHA512 $(sha512sum "/tmp/${e}" | cut -d' ' -f1)" | tee -a "${ebuild_dir}/Manifest"
                rm "/tmp/${e}"
              done
            fi
            break; # We actually only need 1...
          done

      - name: Commit and push changes
        run: |
          ebuild_dir="./${ecn}/${epn}"
          git add ./${ebuild_dir}
          git commit -m "Add ebuilds for new ${epn} releases" && 
          git pull --rebase &&
          git push || true
        if: steps.process_releases.conclusion == 'success'
